config/routes.rb
Rails.application.routes.draw do
  resources :patients

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy!

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      #format.json { head :no_content }    # Removed by Ayush
      format.json { render json: Patient.all, status: :ok }          # Added by Ayush
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      #      params.require(:patient).permit(:first_name, :last_name, :email, :phone_number, :abha_number, :abha_id, :abha_phone_number, :aadhar_number, :aadhar_phone_number, :abha_consent, :abha_otp, :aadhar_otp, :abha_phone_verified, :aadhar_phone_verified, :abha_verified)   # Removed by Ayush
      params.require(:patient).permit(:first_name, :last_name, :email, :phone_number, :abha_number, :abha_id, :abha_phone_number, :aadhar_number, :aadhar_phone_number, :abha_consent, :abha_otp, :aadhar_otp, :abha_phone_verified, :aadhar_phone_verified, :abha_verified, :id)     # Added by Ayush
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'HCX Portal', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Patient Management', patients_path, class: 'nav-link'%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>HCX Portal</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <%= render 'home/header' %>
  <div class="container">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </div>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.number_field :phone_number %>
  </div>

  <div>
    <%= form.label :abha_number, style: "display: block" %>
    <%= form.text_field :abha_number %>
  </div>

  <div>
    <%= form.label :abha_id, style: "display: block" %>
    <%= form.text_field :abha_id %>
  </div>

  <div>
    <%= form.label :abha_phone_number, style: "display: block" %>
    <%= form.number_field :abha_phone_number %>
  </div>

  <div>
    <%= form.label :aadhar_number, style: "display: block" %>
    <%= form.text_field :aadhar_number %>
  </div>

  <div>
    <%= form.label :aadhar_phone_number, style: "display: block" %>
    <%= form.number_field :aadhar_phone_number %>
  </div>

  <div>
    <%= form.label :abha_consent, style: "display: block" %>
    <%= form.text_field :abha_consent %>
  </div>

  <div>
    <%= form.label :abha_otp, style: "display: block" %>
    <%= form.text_field :abha_otp %>
  </div>

  <div>
    <%= form.label :aadhar_otp, style: "display: block" %>
    <%= form.text_field :aadhar_otp %>
  </div>

  <div>
    <%= form.label :abha_phone_verified, style: "display: block" %>
    <%= form.text_field :abha_phone_verified %>
  </div>

  <div>
    <%= form.label :aadhar_phone_verified, style: "display: block" %>
    <%= form.text_field :aadhar_phone_verified %>
  </div>

  <div>
    <%= form.label :abha_verified, style: "display: block" %>
    <%= form.text_field :abha_verified %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>First name:</strong>
    <%= patient.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= patient.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= patient.email %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= patient.phone_number %>
  </p>

  <p>
    <strong>Abha number:</strong>
    <%= patient.abha_number %>
  </p>

  <p>
    <strong>Abha:</strong>
    <%= patient.abha_id %>
  </p>

  <p>
    <strong>Abha phone number:</strong>
    <%= patient.abha_phone_number %>
  </p>

  <p>
    <strong>Aadhar number:</strong>
    <%= patient.aadhar_number %>
  </p>

  <p>
    <strong>Aadhar phone number:</strong>
    <%= patient.aadhar_phone_number %>
  </p>

  <p>
    <strong>Abha consent:</strong>
    <%= patient.abha_consent %>
  </p>

  <p>
    <strong>Abha otp:</strong>
    <%= patient.abha_otp %>
  </p>

  <p>
    <strong>Aadhar otp:</strong>
    <%= patient.aadhar_otp %>
  </p>

  <p>
    <strong>Abha phone verified:</strong>
    <%= patient.abha_phone_verified %>
  </p>

  <p>
    <strong>Aadhar phone verified:</strong>
    <%= patient.aadhar_phone_verified %>
  </p>

  <p>
    <strong>Abha verified:</strong>
    <%= patient.abha_verified %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Show this patient", @patient %> |
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Patients</h1>


<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Email</th>
    <th scope="col">ABHA Number</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @patients.each do |patient| %>
      <tr>
        <th scope="row">1</th>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= patient.email %></td>
        <td><%= patient.abha_number %></td>
        <td><%= link_to "Show this patient", patient %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<!--<div id="patients">-->
  <%# @patients.each do |patient| %>
    <%#= render patient %>
<!--    <p>-->
      <%#= link_to "Show this patient", patient %>
<!--    </p>-->
  <%# end %>
<!--</div>-->

<%= link_to "New patient", new_patient_path, class: "btn btn-primary" %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render "form", patient: @patient %>

<br>

<div>
  <%= link_to "Back to patients", patients_path %>
</div>

app/views/patients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @patient %>

<div>
  <%= link_to "Edit this patient", edit_patient_path(@patient) %> |
  <%= link_to "Back to patients", patients_path %>

  <%= button_to "Destroy this patient", @patient, method: :delete %>
</div>